name: First Workflow
on: [push]

jobs:
  Execute-Shell-Comands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: Check Verison
        run: |
          node --version
          npm --version

  Execture-Bash-Commands:
    runs-on: macos-latest
    steps:
      - name: View Software Version
        run: sw_vers

  Execute-PowerShell-Comands:
    runs-on: windows-latest
    needs: Execute-Shell-Comands
    steps:
      - name: echo "Good OS"
        run: Write-Output "Yo Yo"
      - name: Throw Error
        run: Sladar Stun
