name: First Workflow
on: [push]

jobs:
  Execute-Shell-Comands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: Check Verison
        run: |
          node --version
          npm --version
